from django.db import models

# Create your models here.
class FIR(models.Model):
    fir_no=models.CharField(max_length = 100)
    district=models.CharField(max_length = 100)
    unit_name=models.CharField(max_length = 100)
    
    year = models.IntegerField()
    month = models.IntegerField()
    # offence_from=models.DateTimeField()
    # offence_to=models.DateTimeField()
    registered_on=models.DateTimeField()
    fir_type=models.CharField(max_length=100)
    fir_stage = models.CharField(max_length=100)
    complaint_mode = models.CharField(max_length=100)
    crime_group_name = models.CharField(max_length=100)
    crime_head_name = models.CharField(max_length=100)
    latitude=models.CharField(max_length=100)
    longitude=models.CharField(max_length=100)
    ActSection=models.TextField()
    IOName=models.CharField(max_length=100)
    KGID=models.CharField(max_length=100)
    IOAssigned_Date=models.DateField(null=True, blank=True)
    Internal_IO=models.CharField(max_length=100)
    Place_of_Offence=models.CharField(max_length=100)
    distance_from_ps = models.CharField(max_length=100)
    Beat_Name=models.CharField(max_length=100)
    Village_Area_Name=models.CharField(max_length=100)
    Male=models.IntegerField()
    Female=models.IntegerField()
    Boy=models.IntegerField()
    Girl=models.IntegerField()
    Age=models.IntegerField()
    VICTIM_COUNT = models.IntegerField()
    ACCUSED_COUNT = models.IntegerField()
    Arrested_Male = models.IntegerField()
    Arrested_Female = models.IntegerField()
    Arrested_Count_No = models.IntegerField()
    Accused_ChargeSheeted_Count=models.IntegerField()
    Conviction_Count=models.IntegerField()
    fir_id = models.CharField(max_length=100)
    unit_id = models.CharField(max_length=100)
    crime_no = models.CharField(max_length=100)