# Generated by Django 4.1.13 on 2024-03-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='IOAssigned_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fir',
            name='offence_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fir',
            name='offence_to',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fir',
            name='registered_on',
            field=models.DateTimeField(),
        ),
    ]
