# Generated by Django 4.1.13 on 2024-03-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_fir_ioassigned_date_alter_fir_offence_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='offence_from',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='offence_to',
        ),
    ]
