# Generated by Django 4.1.13 on 2024-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_fir_offence_from_remove_fir_offence_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='IOAssigned_Date',
            field=models.DateField(),
        ),
    ]
