# Generated by Django 4.1.13 on 2024-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_fir_ioassigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='IOAssigned_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
